### ISSUE TITLE
Compatibility with PhpStorm 9.0.2

### ISSUE THREAD

**Issue by MartinMajor** [JanTvrdik/intellij-latte#21]
The newest version of plugin doesn't work in PhpStorm 9.0.2:

```
NoSuchMethodError: Unable to serialize FileEditorManager state: com.jantvrdik.intellij.latte.parser.LatteParserUtil.enter_section_(Lcom/intellij/lang/PsiBuilder;IILcom/intellij/psi/tree/IElementType;Ljava/lang/String;)Lcom/intellij/lang/PsiBuilder$Marker;
NoSuchMethodError: com.jantvrdik.intellij.latte.parser.LatteParserUtil.enter_section_(Lcom/intellij/lang/PsiBuilder;IILcom/intellij/psi/tree/IElementType;Ljava/lang/String;)Lcom/intellij/lang/PsiBuilder$Marker;
```

**Comment by matej21** [comment]
There is an easy fix! it is called "newer PhpStorm" :P

**Comment by MartinMajor** [comment]
Yeah, and then there is the hard and correct one :P

**Comment by matej21** [comment]
fixed 457b9e7817

**Comment by MartinMajor** [comment]
Thanks, I stand you a beer!
